import { useEffect, useState } from "react";
import dayjs from "dayjs";
import Swal from "sweetalert2";
import { useAuth } from "./AuthContext";
import API_ENDPOINTS from "@/apiConfig.jsx";

const parseRows = (result) => { const raw = result?.data?.[0]?.result ?? result?.data; if (!raw) return []; if (Array.isArray(raw)) return raw; try { return JSON.parse(raw); } catch { return []; } };
const date = (value) => value && dayjs(value).isValid() ? dayjs(value).format("MM/DD/YYYY") : "-";

export default function EmployeeShiftApproval() {
  const { user } = useAuth(); const [pending, setPending] = useState([]); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(false);
  const load = async () => { if (!user?.empNo) return; setLoading(true); try { const [pendingResponse, historyResponse] = await Promise.all([fetch(API_ENDPOINTS.shiftChangeApprovalInquiry, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ EMP_NO: user.empNo }) }), fetch(API_ENDPOINTS.shiftChangeApprovalHistory, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ EMP_NO: user.empNo, START_DATE: dayjs().subtract(1, "year").format("YYYY-MM-DD"), END_DATE: dayjs().format("YYYY-MM-DD") }) })]); const [pendingResult, historyResult] = await Promise.all([pendingResponse.json(), historyResponse.json()]); setPending(parseRows(pendingResult).filter((row) => String(row.status ?? row.shiftStatus).toLowerCase() === "pending")); setHistory(parseRows(historyResult)); } catch (error) { console.error(error); Swal.fire("Unable to load approvals", "Please try again.", "error"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [user?.empNo]); // eslint-disable-line react-hooks/exhaustive-deps
  const decide = async (row, approved) => { const confirm = await Swal.fire({ title: approved ? "Approve shift change?" : "Disapprove shift change?", input: "textarea", inputLabel: "Approver remarks", inputPlaceholder: "Optional remarks", showCancelButton: true, confirmButtonText: approved ? "Approve" : "Disapprove", confirmButtonColor: approved ? "#2563eb" : "#dc2626" }); if (!confirm.isConfirmed) return; const response = await fetch(API_ENDPOINTS.approvalShiftChange, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ json_data: JSON.stringify({ json_data: { shiftChangeStamp: row.shiftChangeStamp ?? row.shift_change_stamp ?? row.stamp, appStat: approved ? 1 : 0, appUser: user.empNo, appRemarks: confirm.value?.trim() || "" } }) }) }); const result = await response.json(); if (!response.ok || result.status !== "success") return Swal.fire("Unable to process", result.message || "Please try again.", "error"); await Swal.fire("Saved", approved ? "Shift change approved." : "Shift change disapproved.", "success"); load(); };
  const table = (records, action) => <div className="overflow-auto"><table className="min-w-full text-sm"><thead className="bg-blue-800 text-white"><tr><th className="p-2 text-left">Employee</th><th className="p-2 text-left">Shift Date</th><th className="p-2 text-left">Current Shift</th><th className="p-2 text-left">Requested Shift</th><th className="p-2 text-left">Reason</th><th className="p-2 text-left">Status</th>{action && <th className="p-2">Action</th>}</tr></thead><tbody>{records.map((row, index) => <tr className="border-b" key={row.shiftChangeStamp ?? row.stamp ?? index}><td className="p-2">{row.empName ?? row.emp_name ?? row.empNo}</td><td className="p-2">{date(row.shiftDate ?? row.shift_date)}</td><td className="p-2">{row.currentShiftCode ?? row.current_shift_code}</td><td className="p-2">{row.requestedShiftCode ?? row.requested_shift_code}</td><td className="p-2">{row.remarks ?? row.shiftRemarks}</td><td className="p-2">{row.status ?? row.shiftStatus}</td>{action && <td className="p-2 whitespace-nowrap"><button className="mr-2 rounded bg-blue-700 px-3 py-1 text-white" onClick={() => decide(row, true)}>Approve</button><button className="rounded bg-red-600 px-3 py-1 text-white" onClick={() => decide(row, false)}>Disapprove</button></td>}</tr>)}{!loading && !records.length && <tr><td className="p-6 text-center text-gray-500" colSpan="7">No records found.</td></tr>}</tbody></table></div>;
  return <div className="ml-0 lg:ml-[200px] mt-[80px] min-h-screen bg-gray-100 p-4"><div className="global-div-header-ui"><h1 className="global-div-headertext-ui">Employee Shift Change Approval</h1></div><section className="mt-4 rounded-xl bg-white p-4 shadow"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-blue-900">Pending Applications</h2><button className="rounded border px-3 py-1" onClick={load}>Refresh</button></div>{table(pending, true)}</section><section className="mt-4 rounded-xl bg-white p-4 shadow"><h2 className="mb-3 font-bold text-blue-900">Approval History</h2>{table(history, false)}</section></div>;
}
