import { useEffect, useMemo, useState } from "react";
import dayjs from "dayjs";
import Swal from "sweetalert2";
import { useAuth } from "./AuthContext";
import API_ENDPOINTS from "@/apiConfig.jsx";

const parseRows = (result) => { const raw = result?.data?.[0]?.result ?? result?.data; if (!raw) return []; if (Array.isArray(raw)) return raw; try { return JSON.parse(raw); } catch { return []; } };
const date = (value) => value && dayjs(value).isValid() ? dayjs(value).format("MM/DD/YYYY") : "-";
const statusOf = (row) => String(row?.status ?? row?.shiftStatus ?? row?.shift_status ?? "").trim();
const stampOf = (row) => row?.shiftChangeStamp ?? row?.shift_change_stamp ?? row?.SHIFT_CHANGE_STAMP ?? row?.stamp;
const changeType = (row) => row?.changeShiftType ?? row?.change_shift_type ?? row?.shiftChangeType ?? "Duty";
const shiftText = (row, prefix) => { const code = row?.[`${prefix}ShiftCode`] ?? row?.[`${prefix}_shift_code`] ?? ""; const desc = row?.[`${prefix}ShiftDesc`] ?? row?.[`${prefix}_shift_desc`] ?? row?.[`${prefix}ShiftDescription`] ?? ""; return code ? `${code}${desc ? ` - ${desc}` : ""}` : "Rest Day"; };
const badgeClass = (status) => ({ pending: "bg-amber-100 text-amber-700", approved: "bg-blue-100 text-blue-700", disapproved: "bg-red-100 text-red-700", cancelled: "bg-slate-200 text-slate-700" }[String(status).toLowerCase()] || "bg-slate-100 text-slate-700");

export default function EmployeeShiftApproval() {
  const { user } = useAuth();
  const [pending, setPending] = useState([]); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [selected, setSelected] = useState([]); const [pendingFilters, setPendingFilters] = useState({ search: "", from: "", to: "", type: "all" }); const [historyFilters, setHistoryFilters] = useState({ search: "", from: "", to: "", type: "all", status: "all" });
  const [pendingSort, setPendingSort] = useState({ key: "date", direction: "desc" }); const [historySort, setHistorySort] = useState({ key: "date", direction: "desc" });
  const load = async () => { if (!user?.empNo) return; setLoading(true); setError(""); try { const [pendingResponse, historyResponse] = await Promise.all([fetch(API_ENDPOINTS.shiftChangeApprovalInquiry, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ EMP_NO: user.empNo }) }), fetch(API_ENDPOINTS.shiftChangeApprovalHistory, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ EMP_NO: user.empNo, START_DATE: dayjs().subtract(1, "year").format("YYYY-MM-DD"), END_DATE: "2030-01-01" }) })]); const [pendingResult, historyResult] = await Promise.all([pendingResponse.json(), historyResponse.json()]); setPending(parseRows(pendingResult).filter((row) => statusOf(row).toLowerCase() === "pending")); setHistory(parseRows(historyResult).filter((row) => statusOf(row).toLowerCase() !== "pending")); } catch (loadError) { console.error(loadError); setError("Unable to load Shift Change approvals."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [user?.empNo]); // eslint-disable-line react-hooks/exhaustive-deps
  const sort = (rows, config) => !config.key ? rows : [...rows].sort((a, b) => { const value = (row) => ({ employee: row.empName ?? row.emp_name ?? row.empNo, date: row.shiftDate ?? row.shift_date, type: changeType(row), status: statusOf(row) }[config.key] ?? ""); const av = value(a); const bv = value(b); const compare = config.key === "date" ? dayjs(av).valueOf() - dayjs(bv).valueOf() : String(av).localeCompare(String(bv)); return compare * (config.direction === "asc" ? 1 : -1); });
  const filter = (rows, filters, config) => sort(rows.filter((row) => { const text = `${row.empName ?? row.emp_name ?? ""} ${row.empNo ?? row.empno ?? ""} ${row.remarks ?? row.shiftRemarks ?? ""} ${shiftText(row, "current")} ${shiftText(row, "requested")}`.toLowerCase(); const rowDate = dayjs(row.shiftDate ?? row.shift_date); return (!filters.search || text.includes(filters.search.toLowerCase())) && (!filters.from || !rowDate.isBefore(dayjs(filters.from), "day")) && (!filters.to || !rowDate.isAfter(dayjs(filters.to), "day")) && (filters.type === "all" || changeType(row) === filters.type) && (!filters.status || filters.status === "all" || statusOf(row).toLowerCase() === filters.status); }), config);
  const pendingRows = useMemo(() => filter(pending, pendingFilters, pendingSort), [pending, pendingFilters, pendingSort]); const historyRows = useMemo(() => filter(history, historyFilters, historySort), [history, historyFilters, historySort]);
  useEffect(() => setSelected([]), [pendingRows]);
  const decide = async (rows, indexes, approved) => { if (!indexes.length) return; const action = approved ? "Approve" : "Disapprove"; const confirmation = await Swal.fire({ title: `${action} selected?`, text: `${action} ${indexes.length} shift change application(s)?`, input: "textarea", inputLabel: "Approver's Remarks (optional)", showCancelButton: true, confirmButtonText: action, confirmButtonColor: approved ? "#2563eb" : "#dc2626" }); if (!confirmation.isConfirmed) return; try { for (const index of indexes) { const stamp = stampOf(rows[index]); if (!stamp) throw new Error("A selected record has no shift-change identifier."); const response = await fetch(API_ENDPOINTS.approvalShiftChange, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ json_data: JSON.stringify({ json_data: { shiftChangeStamp: stamp, appStat: approved ? 1 : 0, appUser: user.empNo, appRemarks: confirmation.value?.trim() || "" } }) }) }); const result = await response.json().catch(() => ({})); if (!response.ok || result.status !== "success") throw new Error(result.message || "Unable to process shift change."); } setSelected([]); await load(); await Swal.fire("Saved", `Selected records were ${approved ? "approved" : "disapproved"}.`, "success"); } catch (decisionError) { Swal.fire("Unable to process", decisionError.message || "Please try again.", "error"); } };
  const toggleSort = (setter, current, key) => setter({ key, direction: current.key === key && current.direction === "asc" ? "desc" : "asc" }); const arrow = (config, key) => config.key === key ? (config.direction === "asc" ? " ↑" : " ↓") : "";
  const FilterBar = ({ value, onChange, historyMode }) => <div className="mb-4 grid gap-3 sm:grid-cols-4"><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm lg:col-span-2" placeholder="Search employee, shift, or remarks..." value={value.search} onChange={(event) => onChange({ ...value, search: event.target.value })} /><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm" type="date" value={value.from} onChange={(event) => onChange({ ...value, from: event.target.value })} /><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm" type="date" value={value.to} onChange={(event) => onChange({ ...value, to: event.target.value })} /><select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={value.type} onChange={(event) => onChange({ ...value, type: event.target.value })}><option value="all">All Change Types</option><option value="Duty">Duty</option><option value="Rest Day">Rest Day</option></select>{historyMode && <select className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={value.status} onChange={(event) => onChange({ ...value, status: event.target.value })}><option value="all">All Statuses</option><option value="approved">Approved</option><option value="disapproved">Disapproved</option><option value="cancelled">Cancelled</option></select>}<button className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50" onClick={() => onChange(historyMode ? { search: "", from: "", to: "", type: "all", status: "all" } : { search: "", from: "", to: "", type: "all" })}>Clear Filters</button></div>;
  const Table = ({ rows, selectable = false, sortConfig, setSortConfig }) => <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead className="global-thead-approval"><tr>{selectable && <th className="global-th text-center"><input type="checkbox" checked={rows.length > 0 && selected.length === rows.length} onChange={() => setSelected(selected.length === rows.length ? [] : rows.map((_, index) => index))} /></th>}{[["employee", "Employee"], ["date", "Shift Date"], ["type", "Change Type"], ["current", "Current Shift"], ["requested", "Requested Shift"], ["remarks", "Employee Remarks"], ["status", "Status"]].map(([key, label]) => <th key={key} onClick={() => ["employee", "date", "type", "status"].includes(key) && toggleSort(setSortConfig, sortConfig, key)} className={`global-th whitespace-nowrap text-left ${["employee", "date", "type", "status"].includes(key) ? "cursor-pointer" : ""}`}>{label}{arrow(sortConfig, key)}</th>)}{selectable && <th className="global-th text-center">Action</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={stampOf(row) ?? index} className="border-b border-slate-100 hover:bg-blue-50/40">{selectable && <td className="global-td-approval text-center"><input type="checkbox" checked={selected.includes(index)} onChange={() => setSelected((items) => items.includes(index) ? items.filter((item) => item !== index) : [...items, index])} /></td>}<td className="global-td-approval">{row.empName ?? row.emp_name ?? row.empNo}</td><td className="global-td-approval whitespace-nowrap">{date(row.shiftDate ?? row.shift_date)}</td><td className="global-td-approval"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{changeType(row)}</span></td><td className="global-td-approval">{shiftText(row, "current")}</td><td className="global-td-approval">{changeType(row) === "Rest Day" ? "Rest Day" : shiftText(row, "requested")}</td><td className="global-td-approval max-w-[260px]">{row.remarks ?? row.shiftRemarks ?? "-"}</td><td className="global-td-approval"><span className={`inline-flex min-w-[92px] justify-center rounded-xl px-2 py-1 text-xs font-semibold ${badgeClass(statusOf(row))}`}>{statusOf(row)}</span></td>{selectable && <td className="global-td-approval whitespace-nowrap text-center"><button className="mr-2 rounded-xl bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-blue-700" onClick={() => decide(rows, [index], true)}>Approve</button><button className="rounded-xl bg-red-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-red-700" onClick={() => decide(rows, [index], false)}>Disapprove</button></td>}</tr>)}{!loading && !rows.length && <tr><td colSpan={selectable ? 9 : 7} className="p-8 text-center text-slate-500">No shift change records found.</td></tr>}</tbody></table></div>;
  return <div className="ml-0 lg:ml-[200px] mt-[80px] min-h-screen bg-gray-100 p-4"><div className="global-div-header-ui"><h1 className="global-div-headertext-ui">Employee Shift Change Approval</h1></div>{error && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<section className="mt-4 rounded-xl bg-white p-4 shadow-lg"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-blue-900">Pending Shift Change Applications</h2><p className="text-sm text-slate-500">Select one or more records to approve or disapprove.</p></div><div className="flex flex-wrap gap-2"><button disabled={!selected.length} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40" onClick={() => decide(pendingRows, selected, true)}>Approve Selected</button><button disabled={!selected.length} className="rounded-xl bg-red-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40" onClick={() => decide(pendingRows, selected, false)}>Disapprove Selected</button><button className="rounded-xl border border-slate-300 px-3 py-2 text-xs font-semibold" onClick={load}>Refresh</button></div></div><FilterBar value={pendingFilters} onChange={setPendingFilters} /><Table rows={pendingRows} selectable sortConfig={pendingSort} setSortConfig={setPendingSort} /></section><section className="mt-4 rounded-xl bg-white p-4 shadow-lg"><h2 className="mb-1 font-bold text-blue-900">Shift Change Approval History</h2><p className="mb-4 text-sm text-slate-500">Review previously processed shift change applications.</p><FilterBar historyMode value={historyFilters} onChange={setHistoryFilters} /><Table rows={historyRows} sortConfig={historySort} setSortConfig={setHistorySort} /></section></div>;
}
